name: SSH Tunnel for Home Assistant
options:
  ssh_host: name_of_your_ssh_host
  ssh_user: root
  remote_port: 8123
  local_host: localhost
  local_port: 8123
  private_ssh_key: |
    -----BEGIN RSA PRIVATE KEY-----
    YourPrivateKeyHere
    -----END RSA PRIVATE KEY-----
  other_ssh_options: other_ssh_options

schema:
  ssh_host: str
  ssh_user: str
  remote_port: port
  local_host: str
  local_port: port
  private_ssh_key: str
  other_ssh_options: str

ui:
  private_ssh_key:
    name: Private SSH Key
    description: Paste your SSH private key here
    multiline: true
